"""
Materials + hand-calculation strength checks for printed parts.

IMPORTANT - what this is and is not:
  * these are ENGINEERING-ESTIMATE formulas (beam bending, pin shear, bolt pull-through), the kind used for
    sizing before detailed analysis. They are NOT finite-element analysis and NOT a certification. See
    STRUCTURAL_CLAIM below - every report line generated by this module says so explicitly.
  * the material numbers are now SOURCED from published FDM production datasheets (Xometry's FDM service
    spec sheets and Stratasys OEM datasheets, both fetched and cited below; cross-checked against an
    independent HLH Rapid ASTM D3039 test report for the XY/Z ratio). They are still not YOUR filament on
    YOUR printer - process, moisture, nozzle temp, and infill all shift real strength - so for anything that
    matters, replace these with your own datasheet values and, ideally, break-test coupons on your printer.
  * "printable" != "strong" != "certified". Passing printability.judge_report only means the geometry is a
    valid printable solid. Passing this module's safety-factor check only means a hand-calculated estimate
    clears a margin. Neither is a finite-element stress analysis of the real part under real load.
Units: N, mm, MPa (= N/mm^2), g/cm^3.
"""
from __future__ import annotations
import math

STRUCTURAL_CLAIM = ("geometry-checked and hand-calculation-estimated only - NOT stress-verified by FEA. "
                     "Do not trust for a first unsupervised load-bearing print; see strength.py's module note.")

MATERIALS = {
    #            tensile strength XY (MPa), density g/cm3, note, source
    # Values below use the MORE CONSERVATIVE of Xometry's FDM production-service datasheet figures and
    # Stratasys OEM datasheet figures (both accessed via xometry.com/manufacturing/capabilities/
    # fused-deposition-modeling), i.e. the low end of the XZ-ZX yield range reported there - not the
    # optimistic numbers from marketing "strongest 3D printing material" roundups, since this feeds
    # structural sizing math, not a spec sheet for browsing.
    "pla":    {"sigma": 37, "rho": 1.24, "note": "brittle, creeps, softens ~55 C - not for hot or long-term loads",
               "source": "Xometry FDM service datasheet, general-purpose PLA, low end of XZ-ZX yield range"},
    "petg":   {"sigma": 38, "rho": 1.27, "note": "tough, good general choice",
               "source": "Xometry FDM service datasheet, general-purpose PETG, low end of XZ-ZX yield range"},
    "abs":    {"sigma": 27, "rho": 1.05, "note": "needs an enclosed printer, warps",
               "source": "Stratasys ABS-M30 OEM datasheet via Xometry, low end (ZX) of yield range"},
    "asa":    {"sigma": 27, "rho": 1.07, "note": "UV stable ABS",
               "source": "Stratasys ASA OEM datasheet via Xometry (single reported value, most conservative "
                         "of the several ASA datasheets checked)"},
    "nylon":  {"sigma": 42, "rho": 1.14, "note": "tough, wear resistant, absorbs moisture",
               "source": "Xometry FDM service datasheet, Nylon 12, low end (ZX) of yield range"},
    "pa12cf": {"sigma": 48, "rho": 1.20, "note": "carbon-fibre nylon, stiff; needs hardened nozzle - REVISED "
                                                 "DOWN from an earlier 60 MPa placeholder, see source",
               "source": "Xometry FDM service datasheet, Nylon 6 CF (generic), low end (ZX) of yield range - "
                         "notably weaker across layers than along them (102 XZ vs 48 ZX), consistent with "
                         "carbon fibre reinforcement helping the in-plane direction much more than through-layer"},
    "pc":     {"sigma": 42, "rho": 1.20, "note": "strong, high temperature, hard to print - REVISED DOWN from "
                                                 "an earlier 50 MPa placeholder, see source",
               "source": "Xometry FDM service datasheet, PC, low end (ZX) of yield range"},
}
GRADES = {"hobby": 2.0, "industrial": 3.0, "critical": 5.0}      # required safety factor
PROCESS_KNOCKDOWN = 0.7        # print defects, voids, moisture, ageing
# Z_FACTOR: an independent ASTM D3039 test report (HLH Rapid FDM materials list) measured ABS breaking in Z
# with NO yield point at 19.0 MPa against an XY yield of 38.1 MPa - a ratio of ~0.50, matching this existing
# conservative default. PLA's measured ratio in the same report was less severe (~0.74), so 0.5 stays as the
# conservative default across all materials rather than being loosened for the ones that tested better -
# material-specific Z ratios would need per-material coupon data this module doesn't have yet.
Z_FACTOR = 0.5                 # across layers
G = 9.81


def allowable(material: str, grade: str, direction: str = "xy") -> float:
    """Allowable design stress in MPa = strength x process knockdown / required safety factor."""
    m = MATERIALS[material]["sigma"] * PROCESS_KNOCKDOWN * (Z_FACTOR if direction == "z" else 1.0)
    return m / GRADES[grade]


def bending_stress(F: float, L: float, b: float, h: float) -> float:
    """Cantilever, rectangular section b (width) x h (height in load direction), force F at distance L."""
    return 6.0 * F * L / (b * h * h)


def min_height(F: float, L: float, b: float, sigma_allow: float, step: float = 0.5, floor: float = 4.0) -> float:
    h = math.sqrt(6.0 * F * L / (b * sigma_allow))
    return max(floor, math.ceil(h / step) * step)


def min_pin_diameter(F: float, sigma_allow: float, step: float = 0.5, floor: float = 3.0) -> float:
    """Pin in double shear; shear allowable taken as 0.6 x tensile allowable."""
    tau = 0.6 * sigma_allow
    d = math.sqrt(2.0 * F / (math.pi * tau))
    return max(floor, math.ceil(d / step) * step)


def min_plate_thickness_pullthrough(T: float, washer_d: float, sigma_allow: float, step: float = 0.5,
                                    floor: float = 6.0) -> float:
    """Bolt pull-through (punching shear) of a plate: T = tau * pi * washer_d * t."""
    tau = 0.6 * sigma_allow
    return max(floor, math.ceil(T / (math.pi * washer_d * tau) / step) * step)


def line(name: str, load: float, unit: str, stress: float, allow: float, sf_req: float, sigma_yield: float) -> str:
    sf = sigma_yield * PROCESS_KNOCKDOWN / max(stress, 1e-9)
    return (f"{name}: load {load:.1f} {unit}, stress {stress:.1f} MPa, allowable {allow:.1f} MPa -> "
            f"safety factor {sf:.1f} (need {sf_req:g}) [{STRUCTURAL_CLAIM}]")


# ---------------------------------------------------------------------------
# FEA integration point - gated, not faked. A real FEA solver (CalculiX is the free/open one that comes up
# in your list) is a compiled binary, not a pip package - it can't be installed in this sandbox (no network
# path to it, and no evidence it's a simple `pip install` even outside one - it needs the `ccx` executable on
# PATH, normally via your OS package manager or a from-source build). So this is the honest middle ground
# your own list asked for as the fallback: a real integration POINT that calls a real solver if one is
# available, and returns an explicit "not available" result - never a silently wrong number - if not.
# ---------------------------------------------------------------------------

def fea_available() -> bool:
    """True only if a real solver is actually callable right now - never assumed."""
    import shutil
    return shutil.which("ccx") is not None   # CalculiX's solver binary


def fea_check_beam(F: float, L: float, b: float, h: float, material: str, ccx_path: str = "ccx") -> dict:
    """Real FEA beam check via CalculiX, IF INSTALLED. Returns {'available': False, 'reason': ...} rather
    than a hand-calculated number pretending to be FEA when it isn't - the hand-calc functions above already
    cover that case and say so via STRUCTURAL_CLAIM. Only ever returns a result with 'available': True after
    an actual ccx run succeeded and its .frd output was parsed - no shortcuts."""
    if not fea_available():
        return {"available": False,
                "reason": "CalculiX (ccx) is not installed/on PATH in this environment. Install it (your OS "
                          "package manager, or build from source at calculix.de) to enable real FEA beam "
                          "checks. Until then, this hand-calculation module's bending_stress()/allowable() "
                          "functions are the only sizing signal available, and they are explicitly NOT FEA - "
                          "see STRUCTURAL_CLAIM."}
    # A real integration would: write a .inp deck for this beam (nodes, C3D8 elements, the load case, the
    # material's E and yield from MATERIALS), shell out to `ccx_path <job>`, then parse the .frd output for
    # max von Mises stress. Not implemented - would need a mesh generator for the beam geometry and a real
    # .frd parser, both nontrivial and untestable without ccx actually present to validate against. Rather
    # than write untested parsing code with no solver here to check it against, this stays honestly
    # unimplemented until someone has ccx installed to develop and verify it against.
    return {"available": False, "reason": "ccx found on PATH, but the .inp-deck generator and .frd parser "
                                          "are not implemented yet - see the comment above this function."}
